//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWP_Foreign_Languages_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTeacher
    {
        public int IdServiceTeacher { get; set; }
        public int IdService { get; set; }
        public int IdTeacher { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
