//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWP_Foreign_Languages_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Client = new HashSet<Client>();
            this.LessonTeacher = new HashSet<LessonTeacher>();
            this.Teacher = new HashSet<Teacher>();
        }
    
        public int IdUser { get; set; }
        public string PasswordUser { get; set; }
        public int IdRoleUser { get; set; }
        public string LastNameUser { get; set; }
        public string FirstNameUser { get; set; }
        public string PatronicNameUser { get; set; }
        public string EmailUser { get; set; }
        public string PhoneUser { get; set; }
        public Nullable<System.DateTime> BirthdayUser { get; set; }
        public string SexUser { get; set; }
        public byte[] AvatarUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonTeacher> LessonTeacher { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher> Teacher { get; set; }
    }
}
